=== elmuerte/trese-ample/trese.tracing/profiles/profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.ample-project.net/atf" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:atf="http://www.ample-project.net/atf">
	<element name="profile" type="atf:repositoryProfile"></element>
	<complexType name="repositoryProfile">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="artefactTypes" type="atf:artefactTypes" minOccurs="1" maxOccurs="1"></element>
			<element name="linkTypes" type="atf:linkTypes" minOccurs="1" maxOccurs="1"></element>
		</sequence>
	</complexType>
	<complexType name="artefactTypes">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="artefactType" type="atf:artefactType" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="linkTypes">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="linkType" type="atf:linkType" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="artefactType">
		<sequence>
			<element name="properties" type="atf:artefactTypeProperties" minOccurs="1" maxOccurs="1"></element>
			<element name="instanceProperties" type="atf:instanceProperties" minOccurs="1" maxOccurs="1"></element>
			<element name="inheritance" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence minOccurs="0" maxOccurs="unbounded">
						<choice>
							<element name="typeRef" type="atf:typeRef"></element>
							<element name="nameRef" type="atf:nameRef"></element>
						</choice>
					</sequence>
				</complexType>
			</element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="uuid" type="atf:uuid" use="optional"></attribute>
	</complexType>
	<complexType name="linkType">
		<sequence>
			<element name="properties" type="atf:linkTypeProperties" minOccurs="1" maxOccurs="1"></element>
			<element name="instanceProperties" type="atf:instanceProperties" minOccurs="1" maxOccurs="1"></element>
			<element name="inheritance" minOccurs="1" maxOccurs="1">
				<complexType>
					<sequence minOccurs="0" maxOccurs="unbounded">
						<choice>
							<element name="typeRef" type="atf:typeRef"></element>
							<element name="nameRef" type="atf:nameRef"></element>
						</choice>
					</sequence>
				</complexType>
			</element>
			<element name="scope" type="atf:scope" minOccurs="1" maxOccurs="1"></element>
		</sequence>
		<attribute name="name" type="atf:identifier" use="required"></attribute>
		<attribute name="uuid" type="atf:uuid" use="optional"></attribute>
	</complexType>
	<complexType name="scope">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="scopeArea" type="atf:scopeArea" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="artefactTypeProperties">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="property" type="atf:propertyDisplayName" minOccurs="1" maxOccurs="1"></element>
			<element name="property" type="atf:property" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="linkTypeProperties">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="property" type="atf:propertyForwardDisplayName" minOccurs="1" maxOccurs="1"></element>
			<element name="property" type="atf:propertyBackwardDisplayName" minOccurs="1" maxOccurs="1"></element>
			<element name="property" type="atf:property" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<complexType name="instanceProperties">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="propertyName" type="atf:propertyName" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	<simpleType name="identifier">
		<restriction base="string">
			<minLength value="1"></minLength>
			<pattern value="[\w\.]+"></pattern>
		</restriction>
	</simpleType>
	<simpleType name="displayable">
		<restriction base="string">
			<minLength value="1"></minLength>
			<pattern value="[\w\.\s-]+"></pattern>
		</restriction>
	</simpleType>
	<simpleType name="uuid">
		<restriction base="string">
			<pattern value="\w{8}(-)\w{4}(-)\w{4}(-)\w{4}(-)\w{12}"></pattern>
		</restriction>
	</simpleType>
	<complexType name="scopeArea">
		<sequence minOccurs="1" maxOccurs="1">
			<element name="validSourceTypes" minOccurs="1" maxOccurs="1" type="atf:validTypes">			</element>
			<element name="validTargetTypes" minOccurs="1" maxOccurs="1" type="atf:validTypes">			</element>
		</sequence>
	</complexType>
	<!-- property definition -->
	<complexType name="property">
		<attribute name="name" type="atf:identifier" use="required"></attribute>
		<attribute name="value" type="atf:displayable" use="required"></attribute>
	</complexType>
	<complexType name="propertyName">
		<attribute name="name" type="atf:identifier" use="required"></attribute>
	</complexType>
	<!-- predefined properties -->
	<complexType name="propertyDisplayName">
		<complexContent>
			<restriction base="atf:property">
				<attribute name="name" type="atf:identifier" use="required" fixed="displayname"></attribute>
				<attribute name="value" type="atf:displayable" use="required"></attribute>
			</restriction>
		</complexContent>
	</complexType>
	<complexType name="propertyBackwardDisplayName">
		<complexContent>
			<restriction base="atf:property">
				<attribute name="name" type="atf:identifier" use="required" fixed="displayname.backward"></attribute>
				<attribute name="value" type="atf:displayable" use="required"></attribute>
			</restriction>
		</complexContent>
	</complexType>
	<complexType name="propertyForwardDisplayName">
		<complexContent>
			<restriction base="atf:property">
				<attribute name="name" type="atf:identifier" use="required" fixed="displayname.forward"></attribute>
				<attribute name="value" type="atf:displayable" use="required"></attribute>
			</restriction>
		</complexContent>
	</complexType>
	<complexType name="validTypes">
		<sequence minOccurs="0" maxOccurs="unbounded">
			<choice>
				<element name="typeRef" type="atf:typeRef"></element>
				<element name="nameRef" type="atf:nameRef"></element>
			</choice>
		</sequence>
	</complexType>
	<complexType name="typeRef">
		<attribute name="uuid" type="atf:uuid" use="required"></attribute>
	</complexType>
	<complexType name="nameRef">
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>
</schema>

=== elmuerte/trese-ample/trese.tracing/src/trese/tracing/atf/xadl-profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<atf:profile xmlns:atf="http://www.ample-project.net/atf"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ample-project.net/atf profile.xsd ">
	<atf:artefactTypes>
		<atf:artefactType name="ArchStructure"
			uuid="48128e30-2f23-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname" value="Architecture" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
		</atf:artefactType>
		<atf:artefactType name="Component"
			uuid="2936e730-2e57-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname" value="Component" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
		</atf:artefactType>
		<atf:artefactType name="Connector"
			uuid="2936e731-2e57-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname" value="Connector" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
		</atf:artefactType>
		<atf:artefactType name="Interface"
			uuid="2936e732-2e57-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname" value="Interface" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
		</atf:artefactType>
		<atf:artefactType name="ComponentType"
			uuid="2936e733-2e57-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname" value="Component Type" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
		</atf:artefactType>
		<atf:artefactType name="ConnectorType"
			uuid="2936e734-2e57-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname" value="Connector Type" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
		</atf:artefactType>
		<atf:artefactType name="InterfaceType"
			uuid="2936e735-2e57-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname" value="Interface Type" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
		</atf:artefactType>
	</atf:artefactTypes>
	<atf:linkTypes>
		<atf:linkType name="link" uuid="2936e736-2e57-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname.forward" value="connects to" />
				<atf:property name="displayname.backward" value="connects to" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
			<atf:scope>
				<atf:scopeArea>
					<atf:validSourceTypes>
						<!-- Interface -->
						<atf:typeRef uuid="2936e732-2e57-11de-8c30-0800200c9a66" />
					</atf:validSourceTypes>
					<atf:validTargetTypes>
						<!-- Interface -->
						<atf:typeRef uuid="2936e732-2e57-11de-8c30-0800200c9a66" />
					</atf:validTargetTypes>
				</atf:scopeArea>
			</atf:scope>
		</atf:linkType>
		<atf:linkType name="type" uuid="2936e737-2e57-11de-8c30-0800200c9a66">
			<atf:properties>
				<atf:property name="displayname.forward" value="is of type" />
				<atf:property name="displayname.backward" value="is implementation of" />
			</atf:properties>
			<atf:instanceProperties />
			<atf:inheritance />
			<atf:scope>
				<atf:scopeArea>
					<atf:validSourceTypes>
						<!-- Connector -->
						<atf:typeRef uuid="2936e731-2e57-11de-8c30-0800200c9a66" />
					</atf:validSourceTypes>
					<atf:validTargetTypes>
						<!-- ConnectorType -->
						<atf:typeRef uuid="2936e734-2e57-11de-8c30-0800200c9a66" />
					</atf:validTargetTypes>
				</atf:scopeArea>
				<atf:scopeArea>
					<atf:validSourceTypes>
						<!-- Component -->
						<atf:typeRef uuid="2936e730-2e57-11de-8c30-0800200c9a66" />
					</atf:validSourceTypes>
					<atf:validTargetTypes>
						<!-- ComponentType -->
						<atf:typeRef uuid="2936e733-2e57-11de-8c30-0800200c9a66" />
					</atf:validTargetTypes>
				</atf:scopeArea>
				<atf:scopeArea>
					<atf:validSourceTypes>
						<!-- Interface -->
						<atf:typeRef uuid="2936e732-2e57-11de-8c30-0800200c9a66" />
					</atf:validSourceTypes>
					<atf:validTargetTypes>
						<!-- InterfaceType -->
						<atf:typeRef uuid="2936e735-2e57-11de-8c30-0800200c9a66" />
					</atf:validTargetTypes>
				</atf:scopeArea>
			</atf:scope>
		</atf:linkType>
	</atf:linkTypes>
</atf:profile>
